#!/bin/bash

# Script para visualizar a estrutura de migração

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║     📊 COMPARAÇÃO: BAILEYS vs WABA                      ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "┌─────────────────────────┬─────────────────────────┐"
echo "│       BAILEYS           │         WABA            │"
echo "├─────────────────────────┼─────────────────────────┤"
echo "│ ✅ Gratuito             │ 💰 Pago*               │"
echo "│ 📱 WhatsApp Web         │ 🏢 API Oficial          │"
echo "│ 🔧 QR Code              │ 🔑 Tokens/Credenciais   │"
echo "│ 🏠 Local                │ ☁️  Requer URL pública   │"
echo "│ ⚡ Setup rápido         │ ⏱️  Setup complexo       │"
echo "│ 🔄 Pode desconectar     │ ✅ Estável              │"
echo "│ 🚫 Sem suporte oficial  │ ✅ Suporte oficial      │"
echo "│ 📤 Buffer direto        │ 🔗 URL pública          │"
echo "└─────────────────────────┴─────────────────────────┘"
echo ""
echo "* Meta Cloud API: GRÁTIS até 1000 conversas/mês"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 CASOS DE USO"
echo ""
echo "Baileys é ideal para:"
echo "  ✓ Desenvolvimento e testes"
echo "  ✓ Projetos pessoais"
echo "  ✓ Poucos usuários"
echo "  ✓ Orçamento zero"
echo ""
echo "WABA é ideal para:"
echo "  ✓ Produção"
echo "  ✓ Muitos usuários"
echo "  ✓ Alta confiabilidade necessária"
echo "  ✓ Múltiplos números"
echo "  ✓ Suporte oficial"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 COMANDOS DISPONÍVEIS"
echo ""
echo "  npm run dev        → Modo Baileys (atual)"
echo "  npm run baileys    → Força modo Baileys"
echo "  npm run waba       → Força modo WABA"
echo "  npm run unified    → Detecta do .env"
echo "  npm run setup      → Setup interativo"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTAÇÃO"
echo ""
echo "  README-NEW.md          → Documentação completa"
echo "  MIGRATION_GUIDE.md     → Guia passo-a-passo"
echo "  WABA_SUMMARY.md        → Resumo dos arquivos"
echo "  .env.example           → Template de configuração"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 COMEÇAR AGORA"
echo ""
echo "  Opção 1 (Setup Rápido):"
echo "    $ npm run setup"
echo ""
echo "  Opção 2 (Manual):"
echo "    $ cp .env.example .env"
echo "    $ nano .env  # Configure"
echo "    $ npm run dev"
echo ""
echo "  Opção 3 (Migrar para WABA):"
echo "    $ cat MIGRATION_GUIDE.md  # Leia primeiro!"
echo "    $ npm run waba"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 RECOMENDAÇÃO"
echo ""
echo "  1. Comece com Baileys (já funciona)"
echo "  2. Teste todas as funcionalidades"
echo "  3. Leia o MIGRATION_GUIDE.md"
echo "  4. Configure WABA em paralelo"
echo "  5. Teste WABA em desenvolvimento (use ngrok)"
echo "  6. Migre para produção quando pronto"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
